version: '3'
services:
  TCPServer:
    image: ubuntu:latest
    container_name: cpp
    networks:
      - my-network
    volumes:
      - type: bind
        source: ./
        target: /data
    tty: true


networks:
  my-network: